name: single-cell-sequencing-migration
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - snakemake=7.32.4
  - python=3.9
  - scanpy=1.9.1
  - numpy=1.26.4
  - pandas=1.3.0
  - matplotlib=3.5.1
  - seaborn=0.13.2
  - pandas=1.3.0
  - leidenalg=0.10.2
  - celltypist=1.6.3

